### ISSUE TITLE
Improve reliability and responsiveness

### ISSUE THREAD

**Issue by keithws** [gchokov/homebridge-foobot#18]
Hello,

I am a long-time user of the foobot plugin; first-time contributor. I started working on a fork of this plugin to address some of the issues, mostly to improve responsiveness and reliability. I ended up rewriting it based on the latest plugin template from Homebridge. Since it ended up being a very large change, I published it as another repo and opened this issue to discuss the possibility of a pull request being merged.

Here is the new repo: https://github.com/keithws/homebridge-foobot-multi

I'd really appreciate other people trying this new version and giving feedback!

This new version is a dynamic platform that automatically creates accessories based on the foobots found in each user's API calls. This greatly simplifies the necessary config. Notably, the user's password is no longer required to make API calls, only the API key and the username/email address.

I've also changed the way API calls are made so there are no more "No response" messages nor any "this plugin slows down Homebridge" messages. The API calls are no longer made on demand. When the plugin starts, it kicks off periodic updates in the background. In my testing, I noticed that the manufacturer seems to only update the data in the cloud about every five minutes, but their request limit means you can only check each device every seven minutes, so the checks alternate between (about) five minutes and ten minutes. I say "about" that long because I also adjust the timing to try to align with manufactures timing to have the freshest data possible with background refreshing. People shouldn't go over their 200 request per device per day allotment unless they restart Homebridge many times. And, no worries if they do, the "over limit" response is handled correctly as well.

I believe the only missing feature at this time is the logging of historical data in the Eve format. I am not opposed to adding this feature, however I must admit I don't see the benefit of viewing the data in the Eve app versus viewing the data in the foobot app.

I am open to other feature requests and further collaboration. I really appreciate the work everyone has done on this plugin and I hope I can help make it the best homebridge plugin for foobot!

**Comment by gchokov** [comment]
Thanks for posting!
