### ISSUE TITLE
Error: Cannot find module 'moment'

### ISSUE THREAD

**Issue by twangus** [gchokov/homebridge-foobot#5]
I'm excited to try out this plugin, but I get the following error when I try to run Homebridge after install in the plugin.  Any ideas?

> [5/23/2019, 11:30:24 PM] ====================
> [5/23/2019, 11:30:24 PM] ERROR LOADING PLUGIN homebridge-foobot:
> [5/23/2019, 11:30:24 PM] Error: Cannot find module 'moment'
>    at Function.Module._resolveFilename (module.js:547:15)
>    at Function.Module._load (module.js:474:25)
>    at Module.require (module.js:596:17)
>    at require (internal/module.js:11:18)
>    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-foobot/index.js:10:14)
>    at Module._compile (module.js:652:30)
>    at Object.Module._extensions..js (module.js:663:10)
>    at Module.load (module.js:565:32)
>    at tryModuleLoad (module.js:505:12)
>    at Function.Module._load (module.js:497:3)
>[5/23/2019, 11:30:24 PM] ====================

**Comment by gchokov** [comment]
Hi @twangus - Foobot is using Fakegato plugin for logging air quality data for historical purposes. Fakegato is using moment.js - but in your case, it cannot be resolved. That means that when you've installed the plugin, some of its dependencies failed to install. 

I suggest you running: 
sudo npm install moment -g 

and then again: 
sudo npm install homebridge-foobot -g

The first line will install moment, and the second - reinstall the foobot plugin globally this time. Hopefully this will work.

**Comment by twangus** [comment]
Thanks - manually installing moment seemed to work.  Not sure why the dependencies didn't lead to it being installed in the first place.

Just got the plugin working on my two Foobots, and it seems to be working great so far!

**Comment by gchokov** [comment]
@twangus I am glad you have it working and the plugin suits your needs.

I am closing the issue, and wish you a nice day!
